FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends iw wireless-tools && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY *.py ./
EXPOSE 8501
CMD ["python", "-u", "./main.py"]
