exporter:
  port: 8501
  data_dir: /data

scanner:
  backend: kismet
  interface: wlan1
  kismet_url: http://127.0.0.1:2501
  kismet_username: admin
  kismet_password: "<changeme>"
  poll_interval: 15

