# Kismet site config for Wi-Fi Monitor stack
servername=WiFi Monitor
logtypes=pcapdump,alert
logtemplate=/data/%p_%n_%D-%H-%M-%S
restserver=ALLOWED
httpd_allow_login=TRUE
tracker_device_timeout=3600
max_devices=1000
alertbacklog=1024
source=wlan1:type=linuxwifi
